### ISSUE TITLE
Needed to add the Plugins Element

### ISSUE THREAD

**Issue by jarheadjred** [OlgaMaciaszek/spring-cloud-netflix-demo#2]
https://github.com/OlgaMaciaszek/spring-cloud-netflix-demo/blob/7956f3d29c400acafc8ca229d480be1248a7408d/user-service/pom.xml#L97

Thanks for your great presentation at SpringOne!

I had to add the following pluginRepositories block to resolve sb rc mvn plugin after a fresh git clone ./scripts/runAll.sh

```
      <pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
	</pluginRepositories>```

**Comment by mausamgautam** [comment]
@jarheadjred @OlgaMaciaszek  Yeah, We need plugin in user-service. It failed to compile

**Comment by OlgaMaciaszek** [comment]
Thanks, have added it.
